/**
 **********************************************************************
 * This source code is shared for the sole purpose of demo. Do not copy!
 **********************************************************************
 **/

import { Link } from 'react-router-dom';
import { Grid, Theme, Typography } from '@material-ui/core';
import { makeStyles } from '@material-ui/styles';

import SubCard from 'ui-component/cards/SubCard';

// style constant
const useStyles = makeStyles((theme: Theme) => ({
  root: {
    height: '100%',
    '& .MuiCardHeader-root .MuiTypography-root': {
      fontSize: '1.25rem',
      color: theme.palette.grey[900]
    }
  }
}));

const AdReportsCard = () => {
  const classes = useStyles();

  return (
    <SubCard title="Ad Reports" className={classes.root}>
      <Grid container spacing={2}>
        <Grid item xs={12}>
          <Typography sx={{ color: 'common.black', fontWeight: 500 }}>Analytics you can understand.</Typography>
        </Grid>
        <Grid item xs={12}>
          <Typography variant="body2">
            Our Beta release only offers access to our <b>Ad Reports</b>. Once your accounts are connected, you can view reports for your
            Facebook and Google ads.
            <br />
            <br />
            You can also view leads generated by your campaigns and set them to flow directly to your inbox, pretty neat huh?!
          </Typography>
        </Grid>
        <Grid item xs={12} sx={{ textAlign: 'right' }}>
          <Typography component={Link} to="/account/connectaccounts" color="primary" sx={{ fontWeight: 500, textDecoration: 'none' }}>
            Connect my accounts
          </Typography>
        </Grid>
      </Grid>
    </SubCard>
  );
};

export default AdReportsCard;
